syntax = "proto3";
import "common/data_type.proto";
import "common/common_player.proto";
import "common/common_plot.proto";

option java_package = "com.mcdiamondfire.modapi.messages.clientbound.plot";
option java_multiple_files = true;

// Sent when the player joins a plot. The plot name is a serialized Minecraft component.
message S2CPlotInfo {
  // Represents a player in a plot.
  message PlotPlayer {
    string user_name = 1;
    string user_uuid = 2;
    bool is_owner = 3;
    bool is_developer = 4;
    bool is_builder = 5;
    PlayerMode mode = 6;
  }

  int32 id = 1;
  string name = 2;
  string owner_name = 3;
  string owner_uuid = 4;
  int32 plot_size = 5;
  Region build_region = 6;
  Region code_region = 7;
  APILocation spawn_pos = 8;
  bool is_owner = 11;
  bool is_developer = 12;
  bool is_builder = 13;
  repeated PlotTag tags = 14;
  string handle = 15;
  repeated PlotPlayer players = 16;
}

// Sent as a response to a C2SCodeOperation message,
// error is true if the operation failed (see each operation for details),
// template is not empty only if a get operation succeeded.
message S2CCodeOperationResult {
  // Represents an error that occurred while performing a code operation.
  enum Error {
    NONE = 0;
    NO_PERMISSION = 1;
    NO_LOCATION = 2;
    INVALID_LOCATION = 3;
    NO_ACTION = 4;
    ACTION_NOT_FOUND = 5;
    NO_LOCATION_OR_TEMPLATE = 6;
    INVALID_LOCATION_OR_TEMPLATE = 7;
    TEMPLATE_NOT_FIT = 8;
    INVALID_TEMPLATE = 10;
    INTERNAL_ERROR = 9;
    NO_OPERATION = 11;
  }

  oneof result {
    Error error = 1;
    string template = 2;
  }
}

// Sent as a response to a C2SMultiCodeOperations message,
// contains the results of all operations requested.
message S2CMultiCodeOperationsResult {
  repeated S2CCodeOperationResult results = 1;
}

// Sent when the player joins a plot,
// requires the player to have developer permissions on the plot.
message S2CPlotLineStarters {
  repeated CodeLineStarter line_starter = 1;
}

// Sent when a line starter is added or removed from the plot,
// requires the player to have developer permissions on the plot.
message S2CPlotLineStarterUpdate {
  // Represents an action performed on a line starter.
  enum Action {
    ADD = 0;
    CHANGE = 1;
    REMOVE = 2;
  }
  CodeLineStarter line_starter = 1;
  Action action = 2;
}

// Sent when the plot finishes a lag measurement,
// requires the player to have developer permissions on the plot,
// and be profiling the plot.
message S2CPlotProfiling {
  int32 cpu_usage = 1;
}
