syntax = "proto3";
import "common/common_player.proto";
import "common/common_server.proto";

option java_package = "com.mcdiamondfire.modapi.messages.clientbound.server";
option java_multiple_files = true;

// Sent as a response to a C2SHandshakeRequest message.
message S2CHandshakeResponse {
  enum Error {
    NONE = 0;
    INVALID_PROTOCOL = 1;
    INCOMPATIBLE_PROTOCOL = 2;
    ALREADY_CONNECTED = 3;
    NOT_APPLICABLE = 4;
  }
  // Contains connection metadata after a successful handshake.
  message Success {
    ServerInfo server_info = 1;
  }
  oneof result {
    Error error = 1;
    Success success = 2;
  }
}

// Sent after the player joins the server with their currency and permission information.
message S2CPlayerInfo {
  PlayerCurrency currency = 1;
  PlayerPermissions permissions = 2;
}

// Sent when the player joins the server.
message S2CServerBooster {
  // Represents an active booster.
  message ActiveBooster {
    bool tipped = 1;
    int32 multiplier = 2;
    int64 time_remaining = 3;
    string user_name = 4;
    string user_uuid = 5;
  }

  bool is_active = 1;
  optional ActiveBooster active_booster = 2;
}
