syntax = "proto3";
import "common/data_type.proto";

option java_package = "com.mcdiamondfire.modapi.messages.serverbound.player";
option java_multiple_files = true;

// Teleports the player to the specified location,
// the player must be building or coding, and the location will be clamped to the plot boundaries.
message C2SPlayerTeleport {
  APILocation location = 1;
}

// Switches a player's mode,
// the player must have the permission to do so.
message C2SPlayerMode {
  PlayerMode mode = 1;
}
