syntax = "proto3";

option java_package = "com.mcdiamondfire.modapi.messages.common";
option java_multiple_files = true;

// Represents the player's currency information.
// Ticket bundle names are serialized Minecraft components.
message PlayerCurrency {
  // Represents an unclaimed ticket bundle.
  message TicketBundle {
    string event_name = 1;
    string prize_name = 2;
    int32 ticket_amount = 3;
  }

  int32 tokens = 1;
  int32 tickets = 2;
  repeated TicketBundle ticket_bundles = 3;
  int32 sparks = 4;
}

// Represents the player's permissions, admins will have all permissions set to their highest level.
message PlayerPermissions {
  int32 donor = 1;
  int32 vip = 2;
  int32 qa = 3;
  int32 youtuber = 4;
  int32 support = 5;
  int32 moderation = 6;
  int32 admin = 7;
}
