syntax = "proto3";
import "common/data_type.proto";
import "common/common_code.proto";

option java_package = "com.mcdiamondfire.modapi.messages.common";
option java_multiple_files = true;

// Represents a tag, also known as a category, a plot can have.
enum ApiPlotTag {
  ARCADE = 0;
  VERSUS = 1;
  COMBAT = 2;
  PARKOUR = 3;
  ADVENTURE = 4;
  ROLEPLAY = 5;
  STRATEGY = 6;
  PUZZLE = 7;
  TRIVIA = 8;
  RESOURCES = 9;
  ELIMINATION = 10;
  CREATION = 11;
  MISCELLANEOUS = 12;
}

// Represents a code line starter in the plot.
message ApiLineStarter {
  APILocation location = 1;
  ApiLineStarterType type = 2;
  int32 line_length = 3;
  optional ApiActionReference chest = 4;
}
