syntax = "proto3";

option java_package = "com.mcdiamondfire.modapi.messages.common";
option java_multiple_files = true;

// Represents a reference to an action and its arguments,
// sent when the player opens a code chest and bundled in other messages.
// Display text is serialized as Minecraft components.
message ChestReference {
  // Represents a value type.
  enum Value {
    ANY_TYPE = 0;
    VARIABLE = 1;
    NUMBER = 2;
    TEXT = 3;
    COMPONENT = 4;
    LOCATION = 5;
    VECTOR = 6;
    LIST = 7;
    DICT = 8;
    POTION = 9;
    PARTICLE = 10;
    SOUND = 11;
    SPAWN_EGG = 12;
    PROJECTILE = 13;
    VEHICLE = 14;
    ENTITY_TYPE = 15;
    BLOCK = 16;
    BLOCK_TAG = 17;
    ITEM = 18;
    BYTE = 19;
    NONE = 20;
  }

  // Represents a note in the notes field of an action icon.
  message Note {
    repeated string note = 1;
  }

  // Represents an argument for the chest.
  message Argument {
    Value type = 1;
    bool plural = 2;
    bool optional = 3;
    repeated string description = 4;
    repeated Note notes = 5;
  }

  // Represents a return value of an action.
  message ReturnValue {

    // A standard return value, which contains the value and descriptions fields.
    message Standard {
      Value value_type = 1;
      repeated string descriptions = 2;
    }

    // A simple return value, which only contains a text field.
    message Simple {
      string text = 1;
    }

    oneof return_value_type {
      Standard standard_value = 1;
      Simple simple_value = 2;
    }
  }

  string material = 1;
  string name = 2;
  string sign_name = 3;
  repeated string description = 4;
  repeated Note additional_info = 5;
  optional int32 tags = 6;
  repeated Argument arguments = 7;
  repeated ReturnValue return_values = 8;
  optional bool cancellable = 9;
  optional bool cancelled_automatically = 10;
}
